name: GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  gh-pages:
    name: Publish GitHub Pages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: get latest tag
        uses: actions-ecosystem/action-get-latest-tag@v1
        id: get-latest-tag

      - name: remove v prefix
        run: |
          version=${{ steps.get-latest-tag.outputs.tag }}
          version=${version#"v"}
          echo "VERSION=$version" >> $GITHUB_ENV

      - name: set version to $VERSION
        run: sed -i -e "s/^version = .*/version = \"$VERSION\"/" Cargo.toml

      - uses: actions-rs/cargo@v1
        with:
          command: doc
          args: --no-deps

      - name: create index.html
        run: echo "<meta http-equiv=\"refresh\" content=\"0; url=wirepact_translator\">" > target/doc/index.html

      - name: deploy gh pages
        uses: JamesIves/github-pages-deploy-action@v4.4.0
        with:
          branch: gh-pages
          folder: target/doc
