name: Test

on:
  pull_request:
    branches:
      - '**'

jobs:
  lint_and_test:
    name: Linting and Testing
    runs-on: ubuntu-latest
    services:
      pki:
          image: ghcr.io/wirepact/k8s-pki:latest
          env:
            LOCAL: true
          ports:
            - 8080:8080
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - run: rustup component add clippy

      - uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all-features

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - uses: actions-rs/cargo@v1
        with:
          command: test
